### ISSUE TITLE
If a task is set without force_interval and periodic=False, how often do we expect it to run?

### ISSUE THREAD

**Issue by jMyles** [hangarunderground/tiempo#41]
In the current API, what exactly happens to tasks like this one:

```
@task(priority=1)
def my_task():
    print "How often am I running?"
```
As far as I can tell, such a task will always be void for `get_schedule()` on account of periodic being False:

https://github.com/hangarunderground/tiempo/blob/master/tiempo/task.py#L244

...and thus, it looks like expire_key will always be None here:

https://github.com/hangarunderground/tiempo/blob/master/tiempo/execution.py#L177

So how does this task ever run?

**Comment by vepkenez** [comment]
By definition, that task doesn't run on any predictable schedule.  It runs whenever some code or human tells it to run.

**Comment by vepkenez** [comment]
When it *does* run, it will be in group/priority 1

**Comment by vepkenez** [comment]
this task might be called with .soon() in the context of another task spawning some subtasks, or when specific other code calls for it.

**Comment by jMyles** [comment]
Roger. 

So, it runs in group 1 if .soon() is invoked, but on the caller thread if .now() is invoked, yes?

**Comment by vepkenez** [comment]
yes.

**Comment by jMyles** [comment]
So, another way of saying this is: tasks with periodic=False are not automatically scheduled.  Correct?

**Comment by vepkenez** [comment]
pe·ri·od·ic
ˌpirēˈädik/
adjective
1.
appearing or occurring at intervals

**Comment by vepkenez** [comment]
I don't know.
I could see a task being automatically scheduled but not being periodic.

**Comment by jMyles** [comment]
But given the current API, periodic == automatically scheduled, right?

My initial understanding was that periodic meant that it happened at intervals (ie, every 8 minutes or every 10 seconds), while other scheduled tasks happened only at their designated schedule (every hour at 8 after).

But that's not the current API, correct?

**Comment by vepkenez** [comment]
the current API is like this:

(periodic=True, day=None, hour=None, minute=None)
day, hour, minute args will cause the task to run on every occasion where the day hour or minute matches what is specified.

(force_interval=number_of_seconds)
the task will run every time the number of seconds specified has passed since the last time the task ran.

###IN THE FUTURE###
I could definitely see something to this effect being useful
`task.schedule(year=2016, month=1, day=1)`

**Comment by jMyles** [comment]
Got it.  Thanks man!
